### ISSUE TITLE
Webpack 3

### ISSUE THREAD

**Issue by KeitIG** [danillouz/clean-terminal-webpack-plugin#1]
Hello, first of all, thank you for this plugin, extremly useful :)

could you do a small update to add Webpack 3 as a dependecy? 

Just to avoid: 

<img width="767" alt="screen shot 2017-10-11 at 10 58 32" src="https://user-images.githubusercontent.com/1311607/31431221-512f44f8-ae73-11e7-9180-20321f8ac9e9.png">

Yes, I am a psychopath 😄

**Comment by danillouz** [comment]
Haha, sure np, just published `v1.0.1` :)

Cheers!
