### ISSUE TITLE
Allow pass callback function for custom console message

### ISSUE THREAD

**Issue by jzlxiaohei** [danillouz/clean-terminal-webpack-plugin#18]
1.   after clear console, call the function if passed 
2.  pass compile state (error, warn ...) to the function

**Comment by danillouz** [comment]
Hi @jzlxiaohei , sorry, I completely missed your issue.

Is this still something that you think could be useful?

**Comment by jzlxiaohei** [comment]
Thanks for your reply. We use different solution.
