### ISSUE TITLE
Webpack 4 prints extra line

### ISSUE THREAD

**Issue by saadq** [danillouz/clean-terminal-webpack-plugin#2]
Hey, thanks for this package. Not sure if you're still interested in maintaining/updating this, but with Webpack 4, an extra line seems to get printed at the beginning before the actual content.

Success case:

![screen shot 2018-04-05 at 9 46 15 pm](https://user-images.githubusercontent.com/5678694/38399858-e34cd18e-391a-11e8-9c7f-fc6a0061ccd4.png)

Error case:

![screen shot 2018-04-05 at 9 46 45 pm](https://user-images.githubusercontent.com/5678694/38399856-db82d94e-391a-11e8-8efa-12f7cfde0d3b.png)

**Comment by danillouz** [comment]
Hi, haven't worked webpack for a long time now.. I'll try to make the  time to look into it, but feel free to send a PR. Also the code is stupid simple, so it's very easy to make your own plugin as well :)
