### ISSUE TITLE
npm install could not find @danillouz/eslint-config-nodejs

### ISSUE THREAD

**Issue by adriangodong** [danillouz/clean-terminal-webpack-plugin#20]
Repro:
1. Clone the repository
2. Run `npm install`

**Comment by danillouz** [comment]
Hi Adrian, thanks for reporting this.
I removed the ESLint package recently, because I believed there were no "dependents" on it. Sorry for breaking it!

I have just released `v2.0.6` with a fix.

**Comment by adriangodong** [comment]
Thank you!
